spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: default
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8080

message:
  topic:
    name: test_topic
